apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: todolist-keyvault
  labels: 
    azure.azureauthority.in: aks-apps
    app: asset-manager
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: c8a0a759-3274-498a-af27-dd3dadc55024
    keyvaultName: kv-project-3-zy
    objects:  |
      array:
        - |
          objectName: config
          objectType: secret
          objectAlias: config.json
    tenantId: cf36141c-ddd7-45a7-b073-111f66d0b30c