apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-list-web
  name: todo-list-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-list-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/composedfiles-default: "true"
        io.kompose.service: todo-list-web
    spec:
      containers:
        - image: zhengyugan/todo-list-web:1.0
          name: todo-list-web
          ports:
            - containerPort: 80
              hostPort: 8099
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/config
              name: appsettings
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: appsettings
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: todolist-keyvault
status: {}
